### PR TITLE
auth updates, and minor fixes + simple process handler

### LINKED ISSUE #4: dont use system() for everything
this isn't ideal

### LINKED ISSUE #31: validating license
So they cant just put license = "asdfasdfasdf".

### PR DESCRIPTION
**Pull request by felixangell**
Few things:

* no longer required authenticate publish via the command line
* simple process handler, all instances of `system()` removed (closes #4)
* fixes for license validation (closes #31)

### CODE REVIEW

File: src/process_handler.c [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+bool __create_process(char *command, char *input, ...) {
+    if (num_of_processes >= max_process_count) {
+        printf("yo, wait the fuck up\n");
+        return false;
+    }
+    process_t proc;
+    proc.output = NULL;
+    proc.failed = false;
+
+    FILE *process = popen(command, "w");
```
Comment (MovingtoMars) [inline src/process_handler.c]: This is still unsafe.

You can do things like this:
```
sachiel@jiyuu:[~]$ touch '; rm -rf ~'
sachiel@jiyuu:[~]$ ls
Android    Downloads  Recordings      漫画                 problematic
Anki       gocode     shimeji         アニメ               ; rm -rf ~
axistuff   MultiBit   Steam           addr                 snake.conf
bin        mus        Templates       animu.go             somme.odt
build      Music      Videos          combined.crt         untitled_0.odt
Desktop    Pictures   VirtualBox VMs  ffmpeg_hevc_command
Documents  Public     workspace       history.odt
sachiel@jiyuu:[~]$ 
```

Arkade doesn't sanitize its input. Guess what happens when you run a command involving that file with `popen`.

Comment (felixangell) [inline src/process_handler.c]: @MovingtoMars Add an issue, I'll probably forget
